---
- name: "VPNaaS or SDwan?"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cloud_vpn_name: "domain001"
    cloud_vpn_initiator: "eu-west-2"
  # this will include the variables for the pair (responder, initiator)...
  # we are doing this way for better control of what pair we touch per run/transaction...
  vars_files:
    - "domain/{{ cloud_vpn_name }}/initiator/{{ cloud_vpn_initiator }}.yaml"
    - "domain/{{ cloud_vpn_name }}/responder.yaml"
  roles:
    - role: "prepare"
    - role: "ansible-network.cloud_vpn"