---
- name: "Find responder ami"
  ec2_ami_facts:
    region: "{{ cloud_vpn_responder_aws_region | default(omit) }}"
    owners: "{{ cloud_vpn_responder_image_owner | default(omit) }}"
    filters:
      name: "{{ cloud_vpn_responder_image_name }}"
  register: r_ec2_ami_facts

- name: "Assert that there is at least one image available"
  no_log: true
  vars:
    _ami: "{{ r_ec2_ami_facts | default([]) }}"
  assert:
    that: "_ami | length > 0"

- name: "Define cloud_vpn_responder_image_id as latest image_id found"
  set_fact:
    cloud_vpn_responder_image_id: "{{ (r_ec2_ami_facts.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last).image_id }}"

- name: "cloud_vpn_responder_image_id"
  debug:
    var: cloud_vpn_responder_image_id
    verbosity: 1
