---
- name: "Ensure existence of folder for initiator's ssh key"
  file:
    path: "{{ cloud_vpn_initiator_ssh_private_key_file | dirname }}"
    state: "directory"

- name: "Generate ssh for initiator"
  openssh_keypair:
    path: "{{ cloud_vpn_initiator_ssh_private_key_file }}"
    mode: 0600
