---
cloud_vpn_responder_provisioner_role: "{{ config_map[cloud_vpn_responder_provisioner]['role'] }}"
cloud_vpn_responder_aws_access_key: "{{ config_map[cloud_vpn_responder_provisioner]['access_key'] }}"
cloud_vpn_responder_aws_secret_key: "{{ config_map[cloud_vpn_responder_provisioner]['secret_key'] }}"
cloud_vpn_responder_provider_role: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['role'] }}"
cloud_vpn_responder_key_name: "{{ cloud_vpn_responder_image_id }}"
cloud_vpn_responder_instance_size: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['size'] }}"
cloud_vpn_responder_user: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['user'] }}"
cloud_vpn_responder_ssh_private_key_file: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['key'] }}"
cloud_vpn_responder_image_name: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['name'] }}"
cloud_vpn_responder_image_owner: "{{ config_map[cloud_vpn_responder_provisioner][cloud_vpn_responder_aws_region][cloud_vpn_responder_provider]['owner'] }}"
