---
cloud_vpn_initiator_provisioner_role: "{{ config_map[cloud_vpn_initiator_provisioner]['role'] }}"
cloud_vpn_initiator_aws_access_key: "{{ config_map[cloud_vpn_initiator_provisioner]['access_key'] }}"
cloud_vpn_initiator_aws_secret_key: "{{ config_map[cloud_vpn_initiator_provisioner]['secret_key'] }}"
cloud_vpn_initiator_provider_role: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['role'] }}"
cloud_vpn_initiator_key_name: "{{ cloud_vpn_initiator_image_id }}"
cloud_vpn_initiator_instance_size: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['size'] }}"
cloud_vpn_initiator_user: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['user'] }}"
cloud_vpn_initiator_ssh_private_key_file: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['key'] }}"
cloud_vpn_initiator_image_name: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['name'] }}"
cloud_vpn_initiator_image_owner: "{{ config_map[cloud_vpn_initiator_provisioner][cloud_vpn_initiator_aws_region][cloud_vpn_initiator_provider]['owner'] }}"
