---
- name: "Generate psk for domain (if needed)"
  when: cloud_vpn_psk is not defined
  set_fact:
    cloud_vpn_psk: "{{ cloud_vpn_name | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"

- name: "Generate ssh for initiator"
  shell: "ssh-keygen -m PEM -t rsa -f {{ cloud_vpn_initiator_ssh_private_key_file }} -N ''"
  failed_when: false

- name: "Generate ssh for responder"
  shell: "ssh-keygen -m PEM -t rsa -f {{ cloud_vpn_responder_ssh_private_key_file }} -N ''"
  failed_when: false
