---
config_map:
  name: "domain001"
  psk: "{{ lookup('file', 'keychain/domain/' + cloud_vpn_name, errors='ignore') }}"
  # provisioner specific specifications
  aws:
    access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY_ID') }}" 
    secret_key: "{{ lookup('ENV', 'AWS_SECRET_ACCESS_KEY') }}"
    role: "ansible-network.aws"
    rhel:
      name: "RHEL-7.6*GA*"
      owner: "309956199498"
      size: "t2.medium"
      user: "ec2-user"
      role: "ansible-network.rhel"
      key: "{{ playbook_dir }}/keychain/key/{{ cloud_vpn_name }}"
      tunnel_interface_prefix: "vti"
    csr:
      name: "cisco-CSR*"
      owner: "679593333241"
      size: "t2.medium"
      user: "ec2-user"
      role: "ansible-network.cisco_ios"
      key: "{{ playbook_dir }}/keychain/key/{{ cloud_vpn_name }}"
      tunnel_interface_prefix: "Tunnel"